# Generated by Django 5.2.3 on 2025-06-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter author's name", max_length=100)),
                ('bio_data', models.TextField()),
                ('phone_number', models.CharField(max_length=14)),
            ],
        ),
    ]
