# Generated by Django 5.2.3 on 2025-06-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='fathers_name',
            field=models.CharField(default="father's name", max_length=20),
            preserve_default=False,
        ),
    ]
