# Generated by Django 5.2.3 on 2025-06-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_students_fathers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='fathers_name',
            field=models.CharField(default="your Father's name"),
        ),
    ]
