# Generated by Django 5.2.5 on 2025-08-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brandName',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
    ]
