# Generated by Django 5.2.5 on 2025-08-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_comment_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
