# Generated by Django 5.2.4 on 2025-07-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=256)),
                ('task_description', models.TextField()),
                ('is_task_completed', models.BooleanField(default=False)),
                ('task_assign_date', models.DateTimeField()),
            ],
        ),
    ]
